server:
  port: 8001
logging:
  #path: ${user.dir}/logs/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.149.92:3306/lys_user
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update