spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.149.92:3306/lys_user
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update